// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Clear both role blob caches. Returns a bilingual summary of the cleared
/// blob counts, e.g. `已清空发送缓存 2 个 blob / Cleared send cache (2 blobs)
/// \n已清空接收缓存 0 个 blob / Cleared receive cache (0 blobs)`.
///
/// Errors (without touching the cache) when any session is active, or when a
/// role store cannot be opened, read, cleared, or closed. On Windows the
/// removal fails while a store handle is still open — retry after fully
/// closing the app and any other transfer process.
Future<String> cleanupCache() =>
    RustLib.instance.api.crateApiCacheCleanupCache();
