// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Read the effective config.
Future<ConfigDto> getConfig() => RustLib.instance.api.crateApiConfigGetConfig();

/// Set one config key in the config file and persist it. Valid keys:
/// rendezvous_url, relay_url, data_dir, overwrite. Returns the normalized
/// stored value ("true"/"false" for overwrite).
Future<String> setConfig({required String key, required String value}) =>
    RustLib.instance.api.crateApiConfigSetConfig(key: key, value: value);

/// The effective runtime config (env > file > built-in default).
class ConfigDto {
  final String rendezvousUrl;
  final String relayUrl;
  final String dataDir;
  final bool overwrite;

  const ConfigDto({
    required this.rendezvousUrl,
    required this.relayUrl,
    required this.dataDir,
    required this.overwrite,
  });

  @override
  int get hashCode =>
      rendezvousUrl.hashCode ^
      relayUrl.hashCode ^
      dataDir.hashCode ^
      overwrite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigDto &&
          runtimeType == other.runtimeType &&
          rendezvousUrl == other.rendezvousUrl &&
          relayUrl == other.relayUrl &&
          dataDir == other.dataDir &&
          overwrite == other.overwrite;
}
