// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `event_rx`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Subscribe to the bridge event stream. The returned stream is kept open
/// (and fanned) until the Dart side cancels it.
Stream<BridgeEvent> subscribeEvents() =>
    RustLib.instance.api.crateApiEventsSubscribeEvents();

/// Debug/test helper: push an event onto the bus (T17's real events fan in
/// from core channels instead).
Future<void> emitEvent({required String kind, required String message}) =>
    RustLib.instance.api.crateApiEventsEmitEvent(kind: kind, message: message);

/// Bridge-level event DTO (skeleton: kind + message; T17 adds typed payloads).
class BridgeEvent {
  final String kind;
  final String message;

  const BridgeEvent({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}
