// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Placeholder sync wrapper: demonstrates the drift `RUNTIME.block_on`
/// pattern. Returns a greeting so a Dart smoke test can assert on it.
Future<String> hello({required String name}) =>
    RustLib.instance.api.crateApiHelloHello(name: name);
