// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'events.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_session`, `cancel_flow`, `emit`, `finish_failed`, `live_session_count`, `lookup`, `reject_other`, `role_data_dir`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionCommand`, `SessionState`, `Stage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `hash`

/// Create a session for `role`. The engine (and for the sender the control
/// acceptor) is built now; the flow task waits for the first command.
Future<SessionHandle> createSession({required SessionRole role}) =>
    RustLib.instance.api.crateApiSessionCreateSession(role: role);

/// Prepare `paths` and allocate a pairing code. Valid once, first, on a
/// sender session. Blocks until the code exists (the file inventory and
/// progress events stream out on `watch_transfer` meanwhile).
Future<PreparedSendDto> sendPaths({
  required SessionHandle handle,
  required List<String> paths,
}) =>
    RustLib.instance.api.crateApiSessionSendPaths(handle: handle, paths: paths);

/// Claim `code`'s nameplate, pair with the sender, and return the pending
/// offer. Valid once, first, on a receiver session. Blocks until the offer
/// arrives; the flow then waits for accept/decline/cancel.
Future<OfferDto> receiveTicket({
  required SessionHandle handle,
  required String code,
}) => RustLib.instance.api.crateApiSessionReceiveTicket(
  handle: handle,
  code: code,
);

/// Accept the pending offer and download into `target_dir` (empty = the
/// config data dir's `received/` subdir). Returns as soon as the transfer is
/// dispatched; progress and completion arrive on `watch_transfer`.
Future<void> acceptOffer({
  required SessionHandle handle,
  required String targetDir,
}) => RustLib.instance.api.crateApiSessionAcceptOffer(
  handle: handle,
  targetDir: targetDir,
);

/// Decline the pending offer.
Future<void> declineOffer({
  required SessionHandle handle,
  required String reason,
}) => RustLib.instance.api.crateApiSessionDeclineOffer(
  handle: handle,
  reason: reason,
);

/// Cancel the session from any non-terminal stage: the flow tells the peer,
/// then drives the core session to Cancelled (firing its cancel watch).
Future<void> cancelSession({required SessionHandle handle}) =>
    RustLib.instance.api.crateApiSessionCancelSession(handle: handle);

/// Drop the session handle and stop its flow (aborts a running transfer).
Future<void> disposeSession({required SessionHandle handle}) =>
    RustLib.instance.api.crateApiSessionDisposeSession(handle: handle);

/// Current phase of the session's state machine
/// (created/pending_pair/paired/transferring/done/cancelled/failed).
Future<String> sessionPhase({required SessionHandle handle}) =>
    RustLib.instance.api.crateApiSessionSessionPhase(handle: handle);

/// Stream this session's events (progress + phase) into `updates` until the
/// Dart side cancels the stream. Subscribe early to avoid missing events.
Stream<BridgeEvent> watchTransfer({required SessionHandle handle}) =>
    RustLib.instance.api.crateApiSessionWatchTransfer(handle: handle);

/// One file in an offer or prepared-send inventory (hash is the hex blob
/// hash — a plain String, never the iroh type).
class FileMetaDto {
  final String name;
  final BigInt size;
  final String hash;

  const FileMetaDto({
    required this.name,
    required this.size,
    required this.hash,
  });

  @override
  int get hashCode => name.hashCode ^ size.hashCode ^ hash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileMetaDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size &&
          hash == other.hash;
}

/// The offer a receiver reviews before accepting.
class OfferDto {
  final List<FileMetaDto> files;
  final BigInt totalBytes;

  const OfferDto({required this.files, required this.totalBytes});

  @override
  int get hashCode => files.hashCode ^ totalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OfferDto &&
          runtimeType == other.runtimeType &&
          files == other.files &&
          totalBytes == other.totalBytes;
}

/// A prepared send: the pairing code plus the file inventory.
class PreparedSendDto {
  final String code;
  final List<FileMetaDto> files;
  final BigInt totalBytes;

  const PreparedSendDto({
    required this.code,
    required this.files,
    required this.totalBytes,
  });

  @override
  int get hashCode => code.hashCode ^ files.hashCode ^ totalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreparedSendDto &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          files == other.files &&
          totalBytes == other.totalBytes;
}

/// Opaque handle identifying a session to Dart.
class SessionHandle {
  final BigInt id;

  const SessionHandle({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionHandle &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

/// Role of a session: the sender prepares + serves, the receiver claims +
/// downloads.
enum SessionRole { sender, receiver }
